name: Pull In Custom
on:
  push:
    branches: [ master ]
jobs:

  pull:
    name: youssef update custom
    runs-on: ubuntu-latest
    steps:
    - name: Update Youssef Custom Dir
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.ODOO_SECRET }}
        port: 22
        script: |
          cd /opt/odoo15/projects/youssef/custom/
          chown -R root:root youssef_odoo
          cd /opt/odoo15/projects/youssef/custom/youssef_odoo
          git pull origin master
          git status
          cd /opt/odoo15/projects/youssef/custom/
          chown -R youssef:odoo youssef_odoo
          systemctl restart youssef.service
