name: Pull In Custom
on:
  push:
    branches: [ master ]
jobs:

  pull:
    name: pull on push
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands on odoo server
      uses: appleboy/ssh-action@master
      with:
        host: 3.16.138.14
        username: root
        key: ${{ secrets.ODOO_SECRET }}
        port: 22
        script: |
          whoami
          su -s /bin/bash youssef
          whoami
