name: Pull In Custom
on:
  push:
    branches: [ master ]
jobs:

  pull:
    name: pull on push
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands on odoo server
      uses: appleboy/ssh-action@master
      with:
        host: 3.16.138.14
        username: youssef
        password: 2856017
        port: 22
        script: |
          cd /opt/odoo15/projects/youssef/custom/youssef_odoo/
          git pull origin master
          git status
