name: Pull In Custom
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:

  pull:
    name: youssef update custom
    runs-on: ubuntu-latest
    steps:
    - name: Update Youssef Custom Dir
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.YDEPLOY_SECRET }}
        port: ${{ secrets.PORTS }}
        script: /home/ydeploy/deploy.sh
